export const HEADER_CONTENT =" Eliminate Cyberattack Surface at Lightning Speed";
export const HEADER_CONTENT_2 ="SanerNow's Powerful Tool-Stack Powers Unbreachable Defense";
export const HEADER_CONTENT_3="Plan It Your Way";
export const HEADER_CONTENT_4="Try SanerNow for free"
export const PARAGRAPH_CONTENT ="Leverage a continuous automated, & advanced vulnerability management solution and prevent attacks at scale";
export const PARAGRAPH_CONTENT_2 ="Expose Your Vulnerability Landscape in 5 Minutes, Get 95% Patch & Configuration Compliance in a Week,Harden System COnfigurations and More";
export const PARAGRAPH_CONTENT_3="Trusted by millions, Saner now secure teams all around the world";
export const LEADING_ORGANIZATIONS_TITLE ="Leading Organizations Across 25+ Countries Trust SanerNow";
export const POWERFUL_TOOLS_CONTENT="Powerful tools"
export const SECURITY_AND_IT_HEADER_CONTENT="Reduce the Gap between your Security and IT Operations with a Seamless Integration Solution"
export const SECURITY_AND_IT_SUB_CONTENT="With 160,000+ checks,patches for 400+ native and 3rd party applications,Saner Now provides tools for an end-to-end vulnerability management program"
export const TERMS_CONDITIONS="By signing up,you agree to our Terms and Conditions and Privacy Policy."
export const ENDORSEMENTS_HEADER_TEXT="Endorsements"
export const ENDORSEMENTS_SUB_HEADING="Celebrated Market leader in vulnerability assessment and remediation.The First Solution to do both."
export const CAROUSEL_HEADER_CONTENT_1="Alexa John Abhram"
export const CAROUSEL_SUB_HEADER_CONTENT_1="CEO Of Today"
export const CAROUSEL_PARAGRAPH_CONTENT_1="I've been using Saner Now for a few weeks now,and I have to say,it's been a game-changer for menubar.The app's mood tracking feature has helped me become more awareof my emotions and patterns,and the guided breathing exercises have helped me feel more centered and calm during stressful times."
export const CAROUSEL_HEADER_CONTENT_2="Gain Visibility over IT Assets"
export const CAROUSEL_SUB_HEADER_CONTENT_2="Run real-time IT asset scans and gain complete visibility and control over your organization's IT assets."